# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Truemap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Truemap
  
  # Networking
  # pod 'Alamofire', '~> 5.8'
  
  # Video processing
  # pod 'YouTubePlayer-Swift', '~> 0.8'
  
  # 3D Rendering
  # pod 'SceneKit'
  
  target 'TruemapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TruemapUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
